
#if !defined(_EXCEPTION_CODES_HEADER_DEFINED_)
#define _EXCEPTION_CODES_HEADER_DEFINED_

#define EXCEPTION_CODE_BAD_ALLOCATION       1
#define EXCEPTION_CODE_STORAGE_EXCEPTION    3


#endif

